02 事業をエンジニアリングしよう実装編
ryotaroinagaki/mokumoku pull request #2
Opened 2023-07-19 04:15 UTC by ryotaroinagaki

![image](https://github.com/ryotaroinagaki/mokumoku/assets/125222112/f206303a-6fab-4ff6-b051-3f83a331d1c2)

選択した事業側の課題
サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

また、テスト結果のスクリーンショットを添付します。

ご確認お願い致します。

2023-07-20 05:54 UTC, Tsuchiya2 reviewed
コメントしました。

2023-07-20 05:54 UTC, Tsuchiya2 commented on app/models/user.rb
> +  enum gender: %i(other man woman)
こちらでも良いですが、キーバリュー形式に修正しましょう。
`gender: { other: 1, man: 2, woman: 3}`のようなイメージ（詳細は前の課題で共有された内容等を確認してください）

2023-07-20 05:54 UTC, Tsuchiya2 commented on app/views/events/_event.html.erb
> +        <% if event.only_woman %>
boolean型を使用しているので、only_woman?とした方が直感的（true or falseを期待しているのが分かる）ですね。

2023-07-20 05:54 UTC, Tsuchiya2 commented on app/views/events/_form.html.erb
> +  <% if current_user.gender == 'woman' %>
enumを使用することで使えるメソッドを確認しましょう。
他の箇所も同様です。

2023-07-20 05:54 UTC, Tsuchiya2 commented on app/views/events/show.html.erb
> +      <div class="card mb-3">
インデントが崩れていそうです。

2023-07-21 21:04 UTC, ryotaroinagaki commented
ご指摘いただいた箇所を修正しましたので、ご確認お願いします。
再度、Rspecでのテスト実行し、合格したので結果を添付します。
![image](https://github.com/ryotaroinagaki/mokumoku/assets/125222112/90ccdf53-2ef8-423e-941a-ddc5592286b6)

2023-07-22 03:01 UTC, snrrrns requested changes
講師の中川です！
1点コメントさせていただきました。

2023-07-23 11:53 UTC, ryotaroinagaki commented
ご指摘いただいた箇所を修正しましたので、ご確認お願いします。

2023-07-23 22:46 UTC, busitora approved these changes
LGTM!

2023-07-24 00:41 UTC, merged